# Generated by Django 4.2.1 on 2023-05-25 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_student_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_course1', to='administrator.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='course2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_course2', to='administrator.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='course3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_course3', to='administrator.course'),
        ),
    ]
