# Generated by Django 4.2.1 on 2023-05-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True},
        ),
    ]
