# Generated by Django 4.2.1 on 2023-05-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_student_course1_student_course2_student_course3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
